name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        solution:
          - "./backend/services/Authentication/Authentication.sln"
          - "./backend/services/CreditCards/CreditCards.sln"
          - "./backend/services/InAppNotifications/InAppNotifications.sln"
          - "./backend/services/MoneyTransfer/MoneyTransfer.sln"
        configuration: [ "Debug", "Release" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set Up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Build
        run: dotnet build ${{ matrix.solution }} -c ${{ matrix.configuration }}
